### ISSUE TITLE
Opaque Tag Value

### ISSUE THREAD

**Issue by Ratstail91** [hiperiondev/esp32_toy#1]
https://github.com/hiperiondev/esp32_toy/blob/6f3dd9bd53e227fbe4642ff63bc26f59883a93cc/components/esp32_toy_libs/include/esp32_toy_lib_wifi.h#L43

Hey, I noticed that this line uses `300` as the value for the opaque tag, this will (eventually) clash with Toy.

I don't have it documented yet, but in general my plan was to have the 3 digit numbers for 1st class libraries, and 4 digit numbers for the box game engine stuff.

So I'd tweak this to be 5 digits long. It's not super urgent, just a head's up.

**Comment by hiperiondev** [comment]
It's just a test. I used as reference the existing libraries. As there is no complete documentation yet I am trying to create functional "things" to understand the internal workings.
